name: user_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.20.1
  cloud_firestore: 0.16.0+1
  rxdart: ^0.25.0
  equatable: ^1.0.0
  firebase_core: 0.7.0
  intl: ^0.16.1


